apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 4
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: arjunachari12/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
        livenessProbe:
         httpGet:
            scheme: HTTPS
            path: /
            port: 8080
         initialDelaySeconds: 15
         periodSeconds: 20
        readinessProbe:
         httpGet:
            scheme: HTTPS
            path: /
            port: 8080
         initialDelaySeconds: 5
         periodSeconds: 10
