apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world-controller
spec:
  replicas: 3
  selector:
   app: helloworld
  template:
   metadata:
    labels:
     app: helloworld
   spec:
    containers:
    - name: k8s-demo
      image: arjunachari12/k8s-demo
      ports:
      - name: nodejs
      - containerPort: 3000
